# Generated by Django 3.2.3 on 2021-05-21 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='locker',
            name='featured',
            field=models.TextField(null=True),
        ),
    ]
